extends Node
class_name SUIKA

enum DROPPABLES {SEED = 0, LEAF = 1, DAISY = 2, CARNATION = 3, BLUEBONNET = 4, TULIP = 5, ROSE = 6, SUNFLOWER = 7, SEED_PRESTIGE = 8, LEAF_PRESTIGE = 9, DAISY_PRESTIGE = 10, CARNATION_PRESTIGE = 11, BLUEBONNET_PRESTIGE = 12, TULIP_PRESTIGE = 13, ROSE_PRESTIGE = 14, SUNFLOWER_PRESTIGE = 15}
